---
AWSTemplateFormatVersion: "2010-09-09"
Description: Randy's EC2 ASG template

Resources:
  RandyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.medium
        KeyName: stelligent-u-key-pair
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: "Name"
                Value: rt-launch-template

  RandyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: RandyAutoScalingGroup
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
        - us-east-1d
        - us-east-1e
        - us-east-1f
      LaunchTemplate:
        LaunchTemplateId: !Ref RandyLaunchTemplate
        Version: 1
      DesiredCapacity: 1
      MaxSize: 1
      MinSize: 1
      Tags: 
        - Key: "Name"
          PropagateAtLaunch: false
          Value: "rtate-autoscaling-group"
        - Key: "Group"
          PropagateAtLaunch: true
          Value: "rtate-ec2-autoscaling"
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinSuccessfulInstancesPercent: 100

  ## Exec: aws cloudformation update-stack --stack-name rt-m06u1x1-stack --template-body file://6.1.5_ASG_template.yml --region us-east-1