---
AWSTemplateFormatVersion: "2010-09-09"
Description: Randy's EC2 ASG template

Resources:
  RandyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.medium
        KeyName: stelligent-u-key-pair
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: "Name"
                Value: rt-launch-template

  RandyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: RandyAutoScalingGroup
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
        - us-east-1c
        - us-east-1d
        - us-east-1e
        - us-east-1f
      LaunchTemplate:
        LaunchTemplateId: !Ref RandyLaunchTemplate
        Version: 1
      DesiredCapacity: 1
      MaxSize: 2
      MinSize: 1
      Tags: 
        - Key: "Name"
          PropagateAtLaunch: false
          Value: "rtate-autoscaling-group"
        - Key: "Group"
          PropagateAtLaunch: true
          Value: "rtate-ec2-autoscaling"
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinSuccessfulInstancesPercent: 100

  RandyScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref RandyAutoScalingGroup
      ScalingAdjustment: 1

  RandyCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref RandyScaleOutPolicy
      AlarmDescription: Scale-out if CPU utilization is above 60% over a period of 2 minutes
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref RandyAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 120
      Statistic: Average
      Threshold: 60
    DependsOn: RandyScaleOutPolicy

  ## Exec: aws cloudformation update-stack --stack-name rt-m06u2x1-stack --template-body file://6.3.1_ASG_template.yml --region us-east-1