---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Randy is making his first CFN template from scratch

Parameters:
  BucketName:
    Description: Randy's S3 bucket
    Type: String

Resources:
  RandysS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName