# AWSTemplateFormatVersion: "2010-09-09"
# Description: Randy's lambda template

# Resources:
#   RandyLambdaFunction:
#     Type: AWS::Lambda::Function
#     Properties:
#       Code: 9.1.3_lambda_function.zip
#       # Code: {
#       #   "S3Bucket" : "arn:aws:s3:::rtate-bucket",
#       #   "S3Key": "9.1.3_lambda_function.zip"
#       # }
#       Description: Randy's simple lambda function for lesson 9.1.2
#       Handler: index.handler
#       # PackageType: Zip
#       Role: !GetAtt RandyLambdaRole.Arn
#       Runtime: nodejs14.x
#       Tags: 
#         - Key: "Name"
#           Value: rtate-lambda-function
#       VpcConfig: 
#         SecurityGroupIds:
#           - sg-05d3389a4f581eaed
#         SubnetIds:
#           - subnet-0b1b4886031bb1486
#           - subnet-06add4a05f99fa0b1

#   RandyLambdaRole:
#     Type: AWS::IAM::Role
#     Properties:
#       AssumeRolePolicyDocument:
#         Version: "2012-10-17"
#         Statement:
#           - Effect: Allow
#             Principal:
#               Service:
#                 - lambda.amazonaws.com
#             Action:
#               - 'sts:AssumeRole'
#       Description: String
#       ManagedPolicyArns:
#         - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
#         - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
#         - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
#       Tags: 
#         - Key: "Name"
#           Value: "rtate-lambda-role"

#   RandyLambdaPermission:
#     Type: AWS::Lambda::Permission
#     Properties: 
#       Action: lambda:InvokeFunction
#       FunctionName: !GetAtt RandyLambdaFunction.Arn
#       Principal: apigateway.amazonaws.com
#       SourceAccount: 858633482938
#       # SourceArn: !GetAtt RandyRestApi.Arn

#   RandyApiGatewayMethod:
#     Type: AWS::ApiGateway::Method
#     Properties: 
#       AuthorizationType: NONE
#       # HttpMethod: ANY
#       HttpMethod: POST
#       Integration:
#           # ConnectionId: String
#           # ConnectionType: String
#           # IntegrationHttpMethod: AWS
#           IntegrationHttpMethod: POST
#           # IntegrationResponses: 
#           #   - IntegrationResponse
#           # Type: MOCK
#           Type: AWS_PROXY
#           # Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${!GetAtt RandyLambdaFunction.Arn}/invocations
#           #  https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:858633482938:function:rt-m09u1x2-stack-RandyLambdaFunction-WEPHtgwRlkvt/invocations\nFri
#           Uri: !Sub
#             - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
#             - lambdaArn: !GetAtt RandyLambdaFunction.Arn
#       ResourceId: !GetAtt RandyRestApi.RootResourceId
#       RestApiId: !Ref RandyRestApi

#   RandyRestApi:
#     Type: AWS::ApiGateway::RestApi
#     Properties: 
#       # Body: Json
#       # BodyS3Location: 
#       #   S3Location
#       Description: Randy's simple restApi
#       # EndpointConfiguration:
#       #   EndpointConfiguration
#       Name: RandyRestApi
#       Tags:
#         - Key: "Name"
#           Value: "rtate_restApi"

#   RandyDeployment:
#     Type: AWS::ApiGateway::Deployment
#     Properties:
#       Description: Randy API Deployment
#       RestApiId: !Ref RandyRestApi
#       StageName: RandyStage
#     DependsOn: RandyApiGatewayMethod

# ## Exec: aws cloudformation create-stack --stack-name rt-m09u1x3-stack --template-body file://9.1.3_lambda_template.yml --region us-east-1 --capabilities CAPABILITY_NAMED_IAM

AWSTemplateFormatVersion: '2010-09-09'
Description: Randy's lambda template
Resources:
  RandyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: rtate-bucket
        S3Key: 32b953a2c6e82c00a34d610713c503f7
      Description: Randy's simple lambda function for lesson 9.1.2
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - RandyLambdaRole
        - Arn
      Runtime: nodejs14.x
      Tags:
      - Key: Name
        Value: rtate-lambda-function
      VpcConfig:
        SecurityGroupIds:
        - sg-05d3389a4f581eaed
        SubnetIds:
        - subnet-0b1b4886031bb1486
        - subnet-06add4a05f99fa0b1
  RandyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Description: String
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Tags:
      - Key: Name
        Value: rtate-lambda-role
  RandyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - RandyLambdaFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceAccount: 858633482938
  RandyApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn:
              Fn::GetAtt:
              - RandyLambdaFunction
              - Arn
      ResourceId:
        Fn::GetAtt:
        - RandyRestApi
        - RootResourceId
      RestApiId:
        Ref: RandyRestApi
  RandyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Randy's simple restApi
      Name: RandyRestApi
      Tags:
      - Key: Name
        Value: rtate_restApi
  RandyDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Randy API Deployment
      RestApiId:
        Ref: RandyRestApi
      StageName: RandyStage
    DependsOn: RandyApiGatewayMethod