AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  RegionMap:
    us-east-1:
      vpcId: vpc-09519c2d03f379507
      subnetId: subnet-0b1b4886031bb1486
      imageId: ami-04169656fea786776
    us-east-2:
      vpcId: vpc-04057d6d
      subnetId: subnet-5d6cb210
      imageId: ami-0552e3455b9bc8d50
    us-west-1:
      vpcId: vpc-31660f55
      subnetId: subnet-69787e0d
      imageId: ami-059e7901352ebaef8
    us-west-2:
      vpcId: vpc-86fe7fe1
      subnetId: subnet-c8cceb90
      imageId: ami-51537029
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC2LaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.nano
        IamInstanceProfile: 
          Name: !Ref InstanceProfile
        KeyName: stelligent-u-key-pair
        NetworkInterfaces:
          -
            DeviceIndex: 0
            AssociatePublicIpAddress: True
            SubnetId: !FindInMap [ RegionMap, !Ref "AWS::Region", subnetId ]
        UserData: 
          Fn::Base64: !Sub | 
            #!/bin/bash -xe
            # Install the files and packages from the metadata
            apt update -y
            apt install -y python-setuptools
            mkdir aws-cfn-bootstrap-latest
            curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
            easy_install aws-cfn-bootstrap-latest

            /usr/local/bin/cfn-init -v \
              --stack ${AWS::StackName} \
              --resource EC2 \
              --region ${AWS::Region}

            /usr/local/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource EC2 \
              --region ${AWS::Region}
  EC2:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", imageId ]
    # CreationPolicy:
    #   ResourceSignal:    
    #     Count: 1
    #     Timeout: PT25M
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          sources: 
            /etc/cloudwatchagent: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
          commands:
            installCloudwatch: 
              command: ./install.sh
              cwd: /etc/cloudwatchagent
            launchCloudwatch: 
              command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref RoleCloudWatch
  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Topic 5 - EC2 Lab
      VpcId: !FindInMap [ RegionMap, !Ref "AWS::Region", vpcId ]

## Exec: aws cloudformation create-stack --stack-name rt-m08u1x2-stack --template-body file://8.1.2_cloudwatch_logs_template.yml --region us-east-1 --capabilities CAPABILITY_NAMED_IAM