---
AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles creation

Resources:
  RandyIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  RandyIamRole2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  RandyReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'iam:Get*'
              - 'iam:List*'
            Resource: '*'
      PolicyName: RandyReadOnlyPolicy
      Roles:
        - rt-m03x11-stack-RandyIamRole-DX6VAVXSGF6S
        - !Ref RandyIamRole2

  # Execution: aws cloudformation update-stack --stack-name rt-m03x11-stack --template-body file://3.1.3_template.yml --capabilities CAPABILITY_NAMED_IAM