---
AWSTemplateFormatVersion: "2010-09-09"
Description: Trust Relationships and Assuming Roles Stack

Resources:
  RandyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::858633482938:user/rtate_aa'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/IAMReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

  RandyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rt-stelligent-u-bucket
  
  # Execute: aws cloudformation update-stack --stack-name rt-m03x21-stack --template-body file://3.2.3_template.yml --capabilities CAPABILITY_NAMED_IAM