---
AWSTemplateFormatVersion: "2010-09-09"
Description: Fine-Grained Controls with Policies Stack

Resources:
  RandyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::858633482938:user/rtate_aa'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

  RandyS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rt-stelligent-u-bucket-1

  RandyS3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rt-stelligent-u-bucket-2

  # aws cloudformation create-stack --stack-name rt-m03x31-stack --template-body file://3.3.1_template.yml --capabilities CAPABILITY_NAMED_IAM